#!/usr/bin/env python3
"""Clasifica personas naturales como masculino/femenino según su nombre.

Pipeline (orden de precedencia):
  1. Diccionario KNOWN (override manual)
  2. gender-guesser (base de datos con 40k+ nombres)
  3. Regla por terminación: -A → femenino, -O → masculino
"""
import sqlite3, unicodedata, re
from pathlib import Path

DB = Path.home() / "Projects/Analisis_Concursos_DAFO/concursos_dafo.db"

# ── NORMALIZACIÓN ─────────────────────────────────────────────────────
def normalize(s):
    s = (s or "").strip()
    s = s.upper()
    s = unicodedata.normalize('NFD', s).encode('ascii', 'ignore').decode()
    return s

TOKENS_IGNORAR = {
    "DEL", "DE", "LA", "LAS", "LOS", "EL", "SAN", "SANTA",
    "DON", "DOÑA", "Y", "E", "A", "AL", "POR", "EN", "CON",
    "H", "V", "VAN", "VON",
}

def limpiar_nombres(raw):
    """Limpia y extrae tokens relevantes del campo nombres."""
    if not raw:
        return []
    s = normalize(raw)
    s = s.strip()
    s = s.strip('.')
    s = re.sub(r'[^A-Z\s]', ' ', s)
    tokens = [t for t in s.split() if t and len(t) >= 2 and t not in TOKENS_IGNORAR]
    return tokens


# ── DICCIONARIO KNOWN (override manual) ────────────────────────────
# (mantenido del script original)
KNOWN = {
    "ALEX": "indeterminado",
    "ANGEL": "indeterminado",
    "ANDREA": "femenino",
    "ANDRE": "indeterminado",
    "NICOLAS": "masculino",
    "NICOLE": "femenino",
    "NICOLA": "masculino",
    "RENE": "indeterminado",
    "CARMEN": "femenino",
    "YURI": "indeterminado",
    "YENNY": "femenino",
    "YENIFFER": "femenino",
    "WENDY": "femenino",
    "GLADYS": "femenino",
    "YOLANDA": "femenino",
    "YANIRA": "femenino",
    "YAZMIN": "femenino",
    "YAMILA": "femenino",
    "XIOMARA": "femenino",
    "XIMENA": "femenino",
    "YAELA": "femenino",
    "WILDO": "masculino",
    "WILFREDO": "masculino",
    "WILLIAM": "masculino",
    "VANESA": "femenino",
    "URSULA": "femenino",
    "SANDRA": "femenino",
    "ROXANA": "femenino",
    "ROCIO": "femenino",
    "ROSARIO": "femenino",
    "RAQUEL": "femenino",
    "PATRICIA": "femenino",
    "PAOLA": "femenino",
    "NOEMI": "femenino",
    "NANCY": "femenino",
    "MONICA": "femenino",
    "MILAGROS": "femenino",
    "MERCEDES": "femenino",
    "MARIA": "femenino",
    "MARISOL": "femenino",
    "LUZ": "femenino",
    "LORENA": "femenino",
    "LILIANA": "femenino",
    "LETICIA": "femenino",
    "KATHERINE": "femenino",
    "KAREN": "femenino",
    "JOSEFINA": "femenino",
    "JIMENA": "femenino",
    "JESSICA": "femenino",
    "ISABEL": "femenino",
    "INES": "femenino",
    "GLORIA": "femenino",
    "GISELA": "femenino",
    "GINA": "femenino",
    "FATIMA": "femenino",
    "ESTHER": "femenino",
    "ERIKA": "femenino",
    "ELIANA": "femenino",
    "ELIZABETH": "femenino",
    "ELENA": "femenino",
    "DIANA": "femenino",
    "DENISSE": "femenino",
    "DEBORAH": "femenino",
    "DANITZA": "femenino",
    "CRISTINA": "femenino",
    "CLAUDIA": "femenino",
    "CECILIA": "femenino",
    "CATALINA": "femenino",
    "CARLA": "femenino",
    "BETSABE": "femenino",
    "BETTY": "femenino",
    "BERNARDA": "femenino",
    "BEATRIZ": "femenino",
    "AYLIN": "femenino",
    "AURA": "femenino",
    "ASUCENA": "femenino",
    "ARACELY": "femenino",
    "ANTONELA": "femenino",
    "ANALI": "femenino",
    "ANALUCIA": "femenino",
    "AMELIA": "femenino",
    "ALMENDRA": "femenino",
    "ALICIA": "femenino",
    "ALEJANDRA": "femenino",
    "ALESSANDRA": "femenino",
    "ALBERTINA": "femenino",
    "AIDA": "femenino",
    "ADALI": "femenino",
    "ADA": "femenino",
    "ABIGAIL": "femenino",
    "EDITH": "femenino",
    "RUTH": "femenino",
    "SUSAN": "femenino",
    "SHEYLA": "femenino",
    "SHERYL": "femenino",
    "SHIRLEY": "femenino",
    "SILVIA": "femenino",
    "SONIA": "femenino",
    "TANIA": "femenino",
    "TERESA": "femenino",
    "VERONICA": "femenino",
    "VIVIANA": "femenino",
    "YESENIA": "femenino",
    "ZOILA": "femenino",
    "SOLEDAD": "femenino",
    "SARA": "femenino",
    "ROMINA": "femenino",
    "MARLENI": "femenino",
    "MARITZA": "femenino",
    "MARINA": "femenino",
    "MARGOT": "femenino",
    "MAGNOLIA": "femenino",
    "MACARENA": "femenino",
    "LIZ": "femenino",
    "LIDIA": "femenino",
    "LEYLA": "femenino",
    "LAURA": "femenino",
    "KATIA": "femenino",
    "JUANA": "femenino",
    "JENNY": "femenino",
    "JANET": "femenino",
    "IRENE": "femenino",
    "GRETA": "femenino",
    "GRECIA": "femenino",
    "FRANCHESCA": "femenino",
    "FLOR": "femenino",
    "FABIOLA": "femenino",
    "EVA": "femenino",
    "ESTRELLA": "femenino",
    "ESPERANZA": "femenino",
    "EMILIA": "femenino",
    "DORA": "femenino",
    "DOLORES": "femenino",
    "DENIS": "indeterminado",
    "CYNTHIA": "femenino",
    "CONSUELO": "femenino",
    "CONCEPCION": "femenino",
    "CINTHYA": "femenino",
    "CHARLENE": "femenino",
    "BENILDA": "femenino",
    "ARIANA": "femenino",
    "ANGELA": "femenino",
    "ANETTE": "femenino",
    "ANDRIA": "femenino",
    "ANABELLA": "femenino",
    "ANABEL": "femenino",
    "ANA": "femenino",
    "AMPARO": "femenino",
    "AGUSTINA": "femenino",
    "ADRIANA": "femenino",
    "MELISSA": "femenino",
    "MELINA": "femenino",
    "MIRELLA": "femenino",
    "MYRIAM": "femenino",
    "NATHALY": "femenino",
    "NATHALI": "femenino",
    "NORMA": "femenino",
    "NORA": "femenino",
    "NILDA": "femenino",
    "NIKOLE": "femenino",
    "NELLY": "femenino",
    "NATALY": "femenino",
    "NATALIA": "femenino",
    "NAPOLEON": "masculino",
    "NESTOR": "masculino",
    "NILTON": "masculino",
    "NICOMEDES": "masculino",
    "NICANOR": "masculino",
    "NEREO": "masculino",
    "NEFTALI": "masculino",
    "NATAN": "masculino",
    "NARCISO": "masculino",
    "MOISES": "masculino",
    "MIGUEL": "masculino",
    "MAXIMO": "masculino",
    "MAX": "indeterminado",
    "MAURICIO": "masculino",
    "MATIAS": "masculino",
    "MATEO": "masculino",
    "MARTIN": "masculino",
    "MARIO": "masculino",
    "MARCO": "masculino",
    "MANUEL": "masculino",
    "LUIS": "masculino",
    "LORENZO": "masculino",
    "LEONARDO": "masculino",
    "LEON": "masculino",
    "LEANDRO": "masculino",
    "LAZARO": "masculino",
    "JULIO": "masculino",
    "JOSE": "masculino",
    "JORGE": "masculino",
    "JOAQUIN": "masculino",
    "JESUS": "masculino",
    "JAVIER": "masculino",
    "JAIME": "masculino",
    "IVAN": "masculino",
    "ISRAEL": "masculino",
    "ISMAEL": "masculino",
    "ISAAC": "masculino",
    "IGNACIO": "masculino",
    "HUMBERTO": "masculino",
    "HUGO": "masculino",
    "GONZALO": "masculino",
    "GILMER": "masculino",
    "GERMAN": "masculino",
    "GERSON": "masculino",
    "GERARDO": "masculino",
    "GEOVANNY": "masculino",
    "GENARO": "masculino",
    "GASTON": "masculino",
    "FREDY": "masculino",
    "FREDDY": "masculino",
    "FRANCO": "masculino",
    "FRANCISCO": "masculino",
    "FORTUNATO": "masculino",
    "FERNANDO": "masculino",
    "FELIX": "masculino",
    "FAUSTO": "masculino",
    "ESTEBAN": "masculino",
    "ERNESTO": "masculino",
    "ERICK": "masculino",
    "ENRIQUE": "masculino",
    "EMILIO": "masculino",
    "EMERSON": "masculino",
    "ELVIS": "masculino",
    "ELOY": "masculino",
    "ELMER": "masculino",
    "EDWIN": "masculino",
    "EDUARDO": "masculino",
    "EDGAR": "masculino",
    "EBERT": "masculino",
    "DUBERLY": "masculino",
    "DUBER": "masculino",
    "DORIAN": "masculino",
    "DOMINGO": "masculino",
    "DIONICIO": "masculino",
    "DIEGO": "masculino",
    "DAVID": "masculino",
    "DARWIN": "masculino",
    "DANNY": "masculino",
    "DANIEL": "masculino",
    "CRISTIAN": "masculino",
    "CRISTOBAL": "masculino",
    "CLEMENTE": "masculino",
    "CHRISTIAN": "masculino",
    "CESAR": "masculino",
    "CARLOS": "masculino",
    "BRAYAN": "masculino",
    "BORIS": "masculino",
    "BILLY": "masculino",
    "BENJAMIN": "masculino",
    "BENITO": "masculino",
    "BELISARIO": "masculino",
    "BARTOLOME": "masculino",
    "AUGUSTO": "masculino",
    "ARNULFO": "masculino",
    "ARIEL": "masculino",
    "ARCADIO": "masculino",
    "ANTONY": "masculino",
    "ANTONIO": "masculino",
    "ANSELMO": "masculino",
    "ANDRES": "masculino",
    "ANDERSON": "masculino",
    "AMILCAR": "masculino",
    "AMADOR": "masculino",
    "ALVARO": "masculino",
    "ALONSO": "masculino",
    "ALFREDO": "masculino",
    "ALFONSO": "masculino",
    "ALEXANDER": "masculino",
    "ALEXANDRE": "masculino",
    "ALEJANDRO": "masculino",
    "ALDO": "masculino",
    "ALBERTO": "masculino",
    "ADONIS": "masculino",
    "ADOLFO": "masculino",
    "ADAN": "masculino",
    "ABRAHAM": "masculino",
    "ABEL": "masculino",
    "AARON": "masculino",
    "HANS": "masculino",
    "HELARD": "masculino",
    "HEBER": "masculino",
    "HECTOR": "masculino",
    "HAYDE": "femenino",
    "HAROLD": "masculino",
    "GUILLERMO": "masculino",
    "GUIDO": "masculino",
    "GREGORIO": "masculino",
    "GORKA": "masculino",
    "GODOFREDO": "masculino",
    "GIOVANNI": "masculino",
    "GILMAR": "masculino",
    "GILBERTO": "masculino",
    "GIANCARLO": "masculino",
    "GERALD": "masculino",
    "GEORGINA": "femenino",
    "GEORGE": "masculino",
    "GENESIS": "femenino",
    "GAVINO": "masculino",
    "GARY": "masculino",
    "FRANK": "masculino",
    "FLAVIO": "masculino",
    "FIDEL": "masculino",
    "FELIPE": "masculino",
    "FABRIZIO": "masculino",
    "FABIAN": "masculino",
    "EZEQUIEL": "masculino",
    "EUSEBIO": "masculino",
    "EURIBE": "indeterminado",
    "EUCLIDES": "masculino",
    "ESTANISLAO": "masculino",
    "ESPERT": "masculino",
    "ESAU": "masculino",
    "ERWIN": "masculino",
    "ERICKSON": "masculino",
    "ERASMO": "masculino",
    "ENMANUEL": "masculino",
    "EMILIANO": "masculino",
    "EMIGDIO": "masculino",
    "ELIO": "masculino",
    "ELIM": "masculino",
    "ELIGIO": "masculino",
    "ELIAS": "masculino",
    "ELDER": "masculino",
    "ELARD": "masculino",
    "EFRAIN": "masculino",
    "EDU": "masculino",
    "EDSON": "masculino",
    "EDMUNDO": "masculino",
    "EDILBERTO": "masculino",
    "EDISON": "masculino",
    "EDER": "masculino",
    "EDEN": "masculino",
    "DINO": "masculino",
    "DIMAS": "masculino",
    "DEYVID": "masculino",
    "DEYSER": "masculino",
    "DELFIN": "masculino",
    "DEIVI": "masculino",
    "DARIO": "masculino",
    "DALMIRO": "masculino",
    "DALILA": "femenino",
    "CELSO": "masculino",
    "CANDIDO": "masculino",
    "AUSTRIA": "femenino",
    "ROSA": "femenino",
    "ROSALIA": "femenino",
    "ROSALBA": "femenino",
    "SABINA": "femenino",
    "SALOME": "femenino",
    "SAMANTA": "femenino",
    "SORAYA": "femenino",
    "SUSANA": "femenino",
    "TATIANA": "femenino",
    "TEODORA": "femenino",
    "TRINIDAD": "femenino",
    "VALERIA": "femenino",
    "VILMA": "femenino",
    "VIOLETA": "femenino",
    "VIRGINIA": "femenino",
    "ZORAIDA": "femenino",
    "RENATO": "masculino",
    "REYNALDO": "masculino",
    "REY": "masculino",
    "RICHARD": "masculino",
    "RICARDO": "masculino",
    "RIGOBERTO": "masculino",
    "ROBINSON": "masculino",
    "ROBERTO": "masculino",
    "RODOLFO": "masculino",
    "RODRIGO": "masculino",
    "ROGER": "masculino",
    "ROLANDO": "masculino",
    "ROMAN": "masculino",
    "RONALD": "masculino",
    "RUBEN": "masculino",
    "SALVADOR": "masculino",
    "SAMUEL": "masculino",
    "SANTIAGO": "masculino",
    "SATURNINO": "masculino",
    "SAUL": "masculino",
    "SEBASTIAN": "masculino",
    "SERGIO": "masculino",
    "SEVERINO": "masculino",
    "SIDNEY": "indeterminado",
    "SIMON": "masculino",
    "TEOFILO": "masculino",
    "TEODORO": "masculino",
    "TIMOTEO": "masculino",
    "TOMAS": "masculino",
    "UBALDO": "masculino",
    "ULISES": "masculino",
    "VALENTIN": "masculino",
    "VICTOR": "masculino",
    "VIDAL": "masculino",
    "VICENTE": "masculino",
    "VLADIMIR": "masculino",
    "WALTER": "masculino",
    "WILBER": "masculino",
    "WILDER": "masculino",
    "WILIAM": "masculino",
    "WILSON": "masculino",
    "WINSTON": "masculino",
    "YERSON": "masculino",
    "YOEL": "masculino",
    "ZACARIAS": "masculino",
    "ZOSIMO": "masculino",
    "HENRY": "masculino",
    "JHOSEP": "masculino",
    "JOSEP": "masculino",
    "FRANZ": "masculino",
    "RAFAEL": "masculino",
    "MICHEL": "masculino",
    "EDWARD": "masculino",
    "GILBERTH": "masculino",
    "HIDEKI": "masculino",
    "OSCAR": "masculino",
    "JOEL": "masculino",
    "DENNIS": "masculino",
    "JEDY": "indeterminado",
    "LADY": "femenino",
    "JOHN": "masculino",
    "JOSUE": "masculino",
    "JOHNNY": "masculino",
    "RONNY": "masculino",
    "JHON": "masculino",
    "JHONNY": "masculino",
    "JHONATAN": "masculino",
    "JUNIOR": "masculino",
    "MILER": "masculino",
    "YEFRI": "masculino",
    "YEFRY": "masculino",
    "YEFERSON": "masculino",
    "FRAY": "masculino",
    "KEVIN": "masculino",
    "BRYAN": "masculino",
    "BRANDON": "masculino",
    "BRANDO": "masculino",
    "JORDAN": "masculino",
    "JORDY": "masculino",
    "JHORDY": "masculino",
    "YORDY": "masculino",
    "YORDI": "masculino",
    "JENNI": "femenino",
    "JENNIFER": "femenino",
    "GABY": "femenino",
    "GABRIELA": "femenino",
    "GABRIEL": "masculino",
    "SUGEY": "femenino",
    "SUGHEY": "femenino",
    "LISETH": "femenino",
    "LIZETH": "femenino",
    "MABEL": "femenino",
    "GRACIELA": "femenino",
    "NAZARETH": "femenino",
    "NAZARET": "femenino",
    "CLAUDI": "femenino",
    "ELIBEN": "indeterminado",
    "BRINER": "masculino",
    "VALERI": "femenino",
    "MILUSHKA": "femenino",
    "CAHARIN": "femenino",
    "JOSECARLOS": "masculino",
    "JENRRI": "masculino",
    "KATTY": "femenino",
    "KATY": "femenino",
    "GIOVANNA": "femenino",
    "AURORA": "femenino",
    "LEONOR": "femenino",
    "PERCY": "masculino",
    "PAUL": "masculino",
    "RAUL": "masculino",
    "YUDITH": "femenino",
    "JUDITH": "femenino",
    "DAGOBERTO": "masculino",
    "NORVIL": "masculino",
    "NORBERT": "masculino",
    "NORBERTO": "masculino",
    "YADIRA": "femenino",
    "YESICA": "femenino",
    "YESSICA": "femenino",
    "JHESSICA": "femenino",
    "KIARA": "femenino",
    "MAYRA": "femenino",
    "DAYANA": "femenino",
    "DAYANNA": "femenino",
    "NEYRA": "femenino",
    "NELIDA": "femenino",
    "JACKELINE": "femenino",
    "JACKELIN": "femenino",
    "JACQUELINE": "femenino",
    "KATHERIN": "femenino",
    "CATHERINE": "femenino",
    "LIZZ": "femenino",
    "FLORA": "femenino",
    "MARIBEL": "femenino",
    "MARJORIE": "femenino",
    "MARGARITA": "femenino",
    "MARY": "femenino",
    "MARTHA": "femenino",
    "MARTA": "femenino",
    "BERTHA": "femenino",
    "BERTY": "femenino",
    "DORIS": "femenino",
    "NOE": "masculino",
    "EVARISTO": "masculino",
    "EVER": "masculino",
    "FAUSTINO": "masculino",
    "GHIAN": "masculino",
    "HERACLES": "masculino",
    "HERNAN": "masculino",
    "HILARIO": "masculino",
    "HOMERO": "masculino",
    "HUBER": "masculino",
    "INDIRA": "femenino",
    "JACK": "masculino",
    "JEAN": "masculino",
    "JONATAN": "masculino",
    "JONATHAN": "masculino",
    "JUAN": "masculino",
    "KIMBERLY": "femenino",
    "KLEVER": "masculino",
    "LEONEL": "masculino",
    "LEONIDAS": "masculino",
    "LINO": "masculino",
    "LUCIO": "masculino",
    "MARCELO": "masculino",
    "MARCOS": "masculino",
    "OMAR": "masculino",
    "ORLANDO": "masculino",
    "OSWALDO": "masculino",
    "PABLO": "masculino",
    "PEDRO": "masculino",
    "PELAYO": "masculino",
    "PETER": "masculino",
    "RENZO": "masculino",
    "SANTOS": "masculino",
    "SEGUNDO": "masculino",
    "SILVIO": "masculino",
    "CHRISTINE": "femenino",
    "CRISTINE": "femenino",
    "GISELLE": "femenino",
    "EVELYNE": "femenino",
    "ANDERSSON": "masculino",
    "JULIAN": "masculino",
    "NELSON": "masculino",
    "HERBERT": "masculino",
    "HIDE": "masculino",
    "GILBERT": "masculino",
    "STEPHAN": "masculino",
    "SIGURD": "masculino",
    "EMELIE": "femenino",
    "EMMANUELLE": "femenino",
    "YANESSKA": "femenino",
    "JOSSELYNE": "femenino",
    "JAIR": "masculino",
    "JHOJAN": "masculino",
    "MAGNO": "masculino",
    "GUSTAVO": "masculino",
    "SALIM": "masculino",
    "ANTHONY": "masculino",
    "TORIBIO": "masculino",
    "ARLY": "indeterminado",
    "RENSO": "masculino",
    "ANGELICA": "femenino",
    "ANGELINA": "femenino",
    "YURICO": "indeterminado",
    "ALAN": "masculino",
    "ROY": "masculino",
    "ARMANDO": "masculino",
    "ARTURO": "masculino",
    "PIERO": "masculino",
    "PIERRE": "masculino",
    "BRIAN": "masculino",
    "JIM": "masculino",
    "HENRRY": "masculino",
    "RAMIRO": "masculino",
    "TEOBALDO": "masculino",
    "YON": "masculino",
    "JON": "masculino",
    "LAURENCE": "masculino",
    "JOSELO": "masculino",
    "PASCUAL": "masculino",
    "EVERT": "masculino",
    "ALLISON": "femenino",
    "ALISSON": "femenino",
    "NEY": "masculino",
    "JOSIMAR": "masculino",
    "CELESTE": "femenino",
    "JUSTO": "masculino",
    "SIXTO": "masculino",
    "MAIKOL": "masculino",
    "MILUSKA": "femenino",
    "MARILU": "femenino",
    "GILMA": "femenino",
    "CARIDAD": "femenino",
    "DAGMAR": "femenino",
    "SELENE": "femenino",
    "MELANIE": "femenino",
    "NICOLLE": "femenino",
    "BRIANA": "femenino",
    "DEBORA": "femenino",
    "HILDA": "femenino",
    "IRMA": "femenino",
    "OLGA": "femenino",
    "KARINA": "femenino",
    "ERICA": "femenino",
    "LOREN": "indeterminado",
    "ROCCO": "masculino",
    "VIVIAN": "femenino",
    "LIZBETH": "femenino",
    "LISBETH": "femenino",
    "GENESSIS": "femenino",
    "MAGALY": "femenino",
    "MAGALI": "femenino",
    "SOLE": "femenino",
    "AUXILIADORA": "femenino",
    "BELEN": "femenino",
    "PILAR": "femenino",
    "NIEVES": "femenino",
    "INMACULADA": "femenino",
    "BRENDA": "femenino",
    "ANAMILE": "femenino",
    "ROSEMARIE": "femenino",
    "MILEYDY": "femenino",
    "DAYSI": "femenino",
    "YANINA": "femenino",
    "RUBI": "femenino",
    "ANABELA": "femenino",
    "NADIA": "femenino",
    "NADY": "femenino",
    "ITA": "femenino",
    "BRIGIDA": "femenino",
    "NORKA": "femenino",
    "ANTONIA": "femenino",
    "SOFIA": "femenino",
    "NARCISA": "femenino",
    "ELVA": "femenino",
    "PRISCILA": "femenino",
    "CARMINA": "femenino",
    "DELIA": "femenino",
    "ELVIA": "femenino",
    "FLORENCIA": "femenino",
    "HORTENCIA": "femenino",
    "NEMECIA": "femenino",
    "REBECA": "femenino",
    "TEÓFILA": "femenino",
    "VIDALIA": "femenino",
    "YDA": "femenino",
    "GENOVEVA": "femenino",
    "ELEAZAR": "masculino",
    "MISAEL": "masculino",
    "SAULO": "masculino",
    "SILVANA": "femenino",
    "MAXIMILIANO": "masculino",
    "YISELA": "femenino",
    "LISSET": "femenino",
    "LISET": "femenino",
    "RUFINA": "femenino",
    "HERLINDA": "femenino",
    "SOCORRO": "femenino",
    "AGRIPINA": "femenino",
    "PETRONILA": "femenino",
    "MANUELA": "femenino",
    "SIXTA": "femenino",
    "SEGUNDA": "femenino",
    "PRIMITIVA": "femenino",
    "VICENTA": "femenino",
    "RAMONA": "femenino",
    "LEONORA": "femenino",
    "ELISA": "femenino",
    "ELSA": "femenino",
    "EMMA": "femenino",
    "ESTELA": "femenino",
    "ETSABE": "femenino",
    "IRIS": "femenino",
    "LIZZETH": "femenino",
    "LUZMILA": "femenino",
    "MIRIAM": "femenino",
    "MYRIAN": "femenino",
    "SHIRLY": "femenino",
    "YASMIN": "femenino",
    "YESSENIA": "femenino",
}


# ── REGLA POR TERMINACIÓN ──────────────────────────────────────────
def clasificar_por_regla(name):
    if not name or len(name) <= 2:
        return None
    if name.endswith('A'):
        return 'femenino'
    if name.endswith('O'):
        return 'masculino'
    return None


import gender_guesser.detector as gd
_DETECTOR = gd.Detector(case_sensitive=False)

# ── PIPELINE PRINCIPAL ────────────────────────────────────────────
def _clasificar_token(token):
    """Clasifica un token individual de nombre."""
    if not token or len(token) <= 1:
        return None
    if token in KNOWN:
        return KNOWN[token]
    g = _DETECTOR.get_gender(token)
    MAP = {
        'male': 'masculino', 'female': 'femenino',
        'mostly_male': 'masculino', 'mostly_female': 'femenino',
        'andy': 'indeterminado', 'unknown': None,
    }
    result = MAP.get(g)
    if result:
        return result
    return clasificar_por_regla(token)


def clasificar(nombres_raw):
    tokens = limpiar_nombres(nombres_raw)
    if not tokens:
        return None

    # Estrategia: probar el primer token; si no resulta, probar el último
    candidatos = [tokens[0], tokens[-1]]
    visto = set()
    for tok in candidatos:
        if tok in visto:
            continue
        visto.add(tok)
        res = _clasificar_token(tok)
        if res:
            return res
    return None


# ── MAIN ──────────────────────────────────────────────────────────
if __name__ == "__main__":
    conn = sqlite3.connect(str(DB))

    # Add column if not exists
    try:
        conn.execute("ALTER TABLE persona ADD COLUMN genero TEXT")
    except sqlite3.OperationalError:
        pass

    # Only classify natural persons with NULL genero
    rows = conn.execute(
        "SELECT id, nombres FROM persona WHERE tipo = 'natural' AND genero IS NULL AND nombres IS NOT NULL AND nombres != ''"
    ).fetchall()

    stats = {'masculino': 0, 'femenino': 0, 'indeterminado': 0, None: 0}
    updates = []
    for pid, nombres in rows:
        g = clasificar(nombres)
        stats[g] = stats.get(g, 0) + 1
        updates.append((g, pid))

    conn.executemany("UPDATE persona SET genero = ? WHERE id = ?", updates)
    conn.commit()

    print(f"Personas clasificadas (estaban NULL): {len(updates)}")
    print(f"  Masculino:     {stats.get('masculino', 0)}")
    print(f"  Femenino:      {stats.get('femenino', 0)}")
    print(f"  Indeterminado: {stats.get('indeterminado', 0)}")
    print(f"  Sin clasificar: {stats.get(None, 0)}")

    # Show unclassified sample
    unclassified = conn.execute(
        "SELECT id, nombres FROM persona WHERE tipo = 'natural' AND genero IS NULL AND nombres IS NOT NULL AND nombres != '' LIMIT 30"
    ).fetchall()
    if unclassified:
        print(f"\nSin clasificar (muestra):")
        for pid, nom in unclassified:
            print(f"  [{pid}] {nom}")

    conn.close()
